<?php
namespace Pwnraid\Bnet\Test;

use Pwnraid\Bnet\Utility;

/**
 * @coversDefaultClass \Pwnraid\Bnet\Utility
 */
class UtilityTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @covers ::realmNameToSlug
     */
    public function testRealmNameToSlug()
    {
        $this->assertsame('aegwynn', Utility::realmNameToSlug('Aegwynn'));
        $this->assertsame('aerie-peak', Utility::realmNameToSlug('Aerie Peak'));
        $this->assertsame('agamaggan', Utility::realmNameToSlug('Agamaggan'));
        $this->assertsame('aggra-portugues', Utility::realmNameToSlug('Aggra (Português)'));
        $this->assertsame('aggramar', Utility::realmNameToSlug('Aggramar'));
        $this->assertsame('ahnqiraj', Utility::realmNameToSlug('Ahn\'Qiraj'));
        $this->assertsame('alakir', Utility::realmNameToSlug('Al\'Akir'));
        $this->assertsame('alexstrasza', Utility::realmNameToSlug('Alexstrasza'));
        $this->assertsame('alleria', Utility::realmNameToSlug('Alleria'));
        $this->assertsame('alonsus', Utility::realmNameToSlug('Alonsus'));
        $this->assertsame('amanthul', Utility::realmNameToSlug('Aman\'Thul'));
        $this->assertsame('ambossar', Utility::realmNameToSlug('Ambossar'));
        $this->assertsame('anachronos', Utility::realmNameToSlug('Anachronos'));
        $this->assertsame('anetheron', Utility::realmNameToSlug('Anetheron'));
        $this->assertsame('antonidas', Utility::realmNameToSlug('Antonidas'));
        $this->assertsame('anubarak', Utility::realmNameToSlug('Anub\'arak'));
        $this->assertsame('arakarahm', Utility::realmNameToSlug('Arak-arahm'));
        $this->assertsame('arathi', Utility::realmNameToSlug('Arathi'));
        $this->assertsame('arathor', Utility::realmNameToSlug('Arathor'));
        $this->assertsame('archimonde', Utility::realmNameToSlug('Archimonde'));
        $this->assertsame('area-52', Utility::realmNameToSlug('Area 52'));
        $this->assertsame('argent-dawn', Utility::realmNameToSlug('Argent Dawn'));
        $this->assertsame('arthas', Utility::realmNameToSlug('Arthas'));
        $this->assertsame('arygos', Utility::realmNameToSlug('Arygos'));
        $this->assertsame('ashenvale', Utility::realmNameToSlug('Ashenvale'));
        $this->assertsame('aszune', Utility::realmNameToSlug('Aszune'));
        $this->assertsame('auchindoun', Utility::realmNameToSlug('Auchindoun'));
        $this->assertsame('azjolnerub', Utility::realmNameToSlug('Azjol-Nerub'));
        $this->assertsame('azshara', Utility::realmNameToSlug('Azshara'));
        $this->assertsame('azuregos', Utility::realmNameToSlug('Azuregos'));
        $this->assertsame('azuremyst', Utility::realmNameToSlug('Azuremyst'));
        $this->assertsame('baelgun', Utility::realmNameToSlug('Baelgun'));
        $this->assertsame('balnazzar', Utility::realmNameToSlug('Balnazzar'));
        $this->assertsame('blackhand', Utility::realmNameToSlug('Blackhand'));
        $this->assertsame('blackmoore', Utility::realmNameToSlug('Blackmoore'));
        $this->assertsame('blackrock', Utility::realmNameToSlug('Blackrock'));
        $this->assertsame('blackscar', Utility::realmNameToSlug('Blackscar'));
        $this->assertsame('blades-edge', Utility::realmNameToSlug('Blade\'s Edge'));
        $this->assertsame('bladefist', Utility::realmNameToSlug('Bladefist'));
        $this->assertsame('bloodfeather', Utility::realmNameToSlug('Bloodfeather'));
        $this->assertsame('bloodhoof', Utility::realmNameToSlug('Bloodhoof'));
        $this->assertsame('bloodscalp', Utility::realmNameToSlug('Bloodscalp'));
        $this->assertsame('blutkessel', Utility::realmNameToSlug('Blutkessel'));
        $this->assertsame('booty-bay', Utility::realmNameToSlug('Booty Bay'));
        $this->assertsame('borean-tundra', Utility::realmNameToSlug('Borean Tundra'));
        $this->assertsame('boulderfist', Utility::realmNameToSlug('Boulderfist'));
        $this->assertsame('bronze-dragonflight', Utility::realmNameToSlug('Bronze Dragonflight'));
        $this->assertsame('bronzebeard', Utility::realmNameToSlug('Bronzebeard'));
        $this->assertsame('burning-blade', Utility::realmNameToSlug('Burning Blade'));
        $this->assertsame('burning-legion', Utility::realmNameToSlug('Burning Legion'));
        $this->assertsame('burning-steppes', Utility::realmNameToSlug('Burning Steppes'));
        $this->assertsame('cthun', Utility::realmNameToSlug('C\'Thun'));
        $this->assertsame('chamber-of-aspects', Utility::realmNameToSlug('Chamber of Aspects'));
        $this->assertsame('chants-eternels', Utility::realmNameToSlug('Chants éternels'));
        $this->assertsame('chogall', Utility::realmNameToSlug('Cho\'gall'));
        $this->assertsame('chromaggus', Utility::realmNameToSlug('Chromaggus'));
        $this->assertsame('colinas-pardas', Utility::realmNameToSlug('Colinas Pardas'));
        $this->assertsame('confrerie-du-thorium', Utility::realmNameToSlug('Confrérie du Thorium'));
        $this->assertsame('conseil-des-ombres', Utility::realmNameToSlug('Conseil des Ombres'));
        $this->assertsame('crushridge', Utility::realmNameToSlug('Crushridge'));
        $this->assertsame('culte-de-la-rive-noire', Utility::realmNameToSlug('Culte de la Rive noire'));
        $this->assertsame('daggerspine', Utility::realmNameToSlug('Daggerspine'));
        $this->assertsame('dalaran', Utility::realmNameToSlug('Dalaran'));
        $this->assertsame('dalvengyr', Utility::realmNameToSlug('Dalvengyr'));
        $this->assertsame('darkmoon-faire', Utility::realmNameToSlug('Darkmoon Faire'));
        $this->assertsame('darksorrow', Utility::realmNameToSlug('Darksorrow'));
        $this->assertsame('darkspear', Utility::realmNameToSlug('Darkspear'));
        $this->assertsame('das-konsortium', Utility::realmNameToSlug('Das Konsortium'));
        $this->assertsame('das-syndikat', Utility::realmNameToSlug('Das Syndikat'));
        $this->assertsame('deathguard', Utility::realmNameToSlug('Deathguard'));
        $this->assertsame('deathweaver', Utility::realmNameToSlug('Deathweaver'));
        $this->assertsame('deathwing', Utility::realmNameToSlug('Deathwing'));
        $this->assertsame('deepholm', Utility::realmNameToSlug('Deepholm'));
        $this->assertsame('defias-brotherhood', Utility::realmNameToSlug('Defias Brotherhood'));
        $this->assertsame('dentarg', Utility::realmNameToSlug('Dentarg'));
        $this->assertsame('der-mithrilorden', Utility::realmNameToSlug('Der Mithrilorden'));
        $this->assertsame('der-rat-von-dalaran', Utility::realmNameToSlug('Der Rat von Dalaran'));
        $this->assertsame('der-abyssische-rat', Utility::realmNameToSlug('Der abyssische Rat'));
        $this->assertsame('destromath', Utility::realmNameToSlug('Destromath'));
        $this->assertsame('dethecus', Utility::realmNameToSlug('Dethecus'));
        $this->assertsame('die-aldor', Utility::realmNameToSlug('Die Aldor'));
        $this->assertsame('die-arguswacht', Utility::realmNameToSlug('Die Arguswacht'));
        $this->assertsame('die-nachtwache', Utility::realmNameToSlug('Die Nachtwache'));
        $this->assertsame('die-silberne-hand', Utility::realmNameToSlug('Die Silberne Hand'));
        $this->assertsame('die-todeskrallen', Utility::realmNameToSlug('Die Todeskrallen'));
        $this->assertsame('die-ewige-wacht', Utility::realmNameToSlug('Die ewige Wacht'));
        $this->assertsame('doomhammer', Utility::realmNameToSlug('Doomhammer'));
        $this->assertsame('draenor', Utility::realmNameToSlug('Draenor'));
        $this->assertsame('dragonblight', Utility::realmNameToSlug('Dragonblight'));
        $this->assertsame('dragonmaw', Utility::realmNameToSlug('Dragonmaw'));
        $this->assertsame('drakthul', Utility::realmNameToSlug('Drak\'thul'));
        $this->assertsame('drekthar', Utility::realmNameToSlug('Drek\'Thar'));
        $this->assertsame('dun-modr', Utility::realmNameToSlug('Dun Modr'));
        $this->assertsame('dun-morogh', Utility::realmNameToSlug('Dun Morogh'));
        $this->assertsame('dunemaul', Utility::realmNameToSlug('Dunemaul'));
        $this->assertsame('durotan', Utility::realmNameToSlug('Durotan'));
        $this->assertsame('earthen-ring', Utility::realmNameToSlug('Earthen Ring'));
        $this->assertsame('echsenkessel', Utility::realmNameToSlug('Echsenkessel'));
        $this->assertsame('eitrigg', Utility::realmNameToSlug('Eitrigg'));
        $this->assertsame('eldrethalas', Utility::realmNameToSlug('Eldre\'Thalas'));
        $this->assertsame('elune', Utility::realmNameToSlug('Elune'));
        $this->assertsame('emerald-dream', Utility::realmNameToSlug('Emerald Dream'));
        $this->assertsame('emeriss', Utility::realmNameToSlug('Emeriss'));
        $this->assertsame('eonar', Utility::realmNameToSlug('Eonar'));
        $this->assertsame('eredar', Utility::realmNameToSlug('Eredar'));
        $this->assertsame('eversong', Utility::realmNameToSlug('Eversong'));
        $this->assertsame('executus', Utility::realmNameToSlug('Executus'));
        $this->assertsame('exodar', Utility::realmNameToSlug('Exodar'));
        $this->assertsame('festung-der-sturme', Utility::realmNameToSlug('Festung der Stürme'));
        $this->assertsame('fordragon', Utility::realmNameToSlug('Fordragon'));
        $this->assertsame('forscherliga', Utility::realmNameToSlug('Forscherliga'));
        $this->assertsame('frostmane', Utility::realmNameToSlug('Frostmane'));
        $this->assertsame('frostmourne', Utility::realmNameToSlug('Frostmourne'));
        $this->assertsame('frostwhisper', Utility::realmNameToSlug('Frostwhisper'));
        $this->assertsame('frostwolf', Utility::realmNameToSlug('Frostwolf'));
        $this->assertsame('galakrond', Utility::realmNameToSlug('Galakrond'));
        $this->assertsame('garona', Utility::realmNameToSlug('Garona'));
        $this->assertsame('garrosh', Utility::realmNameToSlug('Garrosh'));
        $this->assertsame('genjuros', Utility::realmNameToSlug('Genjuros'));
        $this->assertsame('ghostlands', Utility::realmNameToSlug('Ghostlands'));
        $this->assertsame('gilneas', Utility::realmNameToSlug('Gilneas'));
        $this->assertsame('goldrinn', Utility::realmNameToSlug('Goldrinn'));
        $this->assertsame('gordunni', Utility::realmNameToSlug('Gordunni'));
        $this->assertsame('gorgonnash', Utility::realmNameToSlug('Gorgonnash'));
        $this->assertsame('greymane', Utility::realmNameToSlug('Greymane'));
        $this->assertsame('grim-batol', Utility::realmNameToSlug('Grim Batol'));
        $this->assertsame('grom', Utility::realmNameToSlug('Grom'));
        $this->assertsame('guldan', Utility::realmNameToSlug('Gul\'dan'));
        $this->assertsame('hakkar', Utility::realmNameToSlug('Hakkar'));
        $this->assertsame('haomarush', Utility::realmNameToSlug('Haomarush'));
        $this->assertsame('hellfire', Utility::realmNameToSlug('Hellfire'));
        $this->assertsame('hellscream', Utility::realmNameToSlug('Hellscream'));
        $this->assertsame('howling-fjord', Utility::realmNameToSlug('Howling Fjord'));
        $this->assertsame('hyjal', Utility::realmNameToSlug('Hyjal'));
        $this->assertsame('illidan', Utility::realmNameToSlug('Illidan'));
        $this->assertsame('jaedenar', Utility::realmNameToSlug('Jaedenar'));
        $this->assertsame('kaelthas', Utility::realmNameToSlug('Kael\'thas'));
        $this->assertsame('karazhan', Utility::realmNameToSlug('Karazhan'));
        $this->assertsame('kargath', Utility::realmNameToSlug('Kargath'));
        $this->assertsame('kazzak', Utility::realmNameToSlug('Kazzak'));
        $this->assertsame('kelthuzad', Utility::realmNameToSlug('Kel\'Thuzad'));
        $this->assertsame('khadgar', Utility::realmNameToSlug('Khadgar'));
        $this->assertsame('khaz-modan', Utility::realmNameToSlug('Khaz Modan'));
        $this->assertsame('khazgoroth', Utility::realmNameToSlug('Khaz\'goroth'));
        $this->assertsame('kiljaeden', Utility::realmNameToSlug('Kil\'jaeden'));
        $this->assertsame('kilrogg', Utility::realmNameToSlug('Kilrogg'));
        $this->assertsame('kirin-tor', Utility::realmNameToSlug('Kirin Tor'));
        $this->assertsame('korgall', Utility::realmNameToSlug('Kor\'gall'));
        $this->assertsame('kragjin', Utility::realmNameToSlug('Krag\'jin'));
        $this->assertsame('krasus', Utility::realmNameToSlug('Krasus'));
        $this->assertsame('kul-tiras', Utility::realmNameToSlug('Kul Tiras'));
        $this->assertsame('kult-der-verdammten', Utility::realmNameToSlug('Kult der Verdammten'));
        $this->assertsame('la-croisade-ecarlate', Utility::realmNameToSlug('La Croisade écarlate'));
        $this->assertsame('laughing-skull', Utility::realmNameToSlug('Laughing Skull'));
        $this->assertsame('les-clairvoyants', Utility::realmNameToSlug('Les Clairvoyants'));
        $this->assertsame('les-sentinelles', Utility::realmNameToSlug('Les Sentinelles'));
        $this->assertsame('lich-king', Utility::realmNameToSlug('Lich King'));
        $this->assertsame('lightbringer', Utility::realmNameToSlug('Lightbringer'));
        $this->assertsame('lightnings-blade', Utility::realmNameToSlug('Lightning\'s Blade'));
        $this->assertsame('lordaeron', Utility::realmNameToSlug('Lordaeron'));
        $this->assertsame('los-errantes', Utility::realmNameToSlug('Los Errantes'));
        $this->assertsame('lothar', Utility::realmNameToSlug('Lothar'));
        $this->assertsame('madmortem', Utility::realmNameToSlug('Madmortem'));
        $this->assertsame('magtheridon', Utility::realmNameToSlug('Magtheridon'));
        $this->assertsame('malganis', Utility::realmNameToSlug('Mal\'Ganis'));
        $this->assertsame('malfurion', Utility::realmNameToSlug('Malfurion'));
        $this->assertsame('malorne', Utility::realmNameToSlug('Malorne'));
        $this->assertsame('malygos', Utility::realmNameToSlug('Malygos'));
        $this->assertsame('mannoroth', Utility::realmNameToSlug('Mannoroth'));
        $this->assertsame('marecage-de-zangar', Utility::realmNameToSlug('Marécage de Zangar'));
        $this->assertsame('mazrigos', Utility::realmNameToSlug('Mazrigos'));
        $this->assertsame('medivh', Utility::realmNameToSlug('Medivh'));
        $this->assertsame('minahonda', Utility::realmNameToSlug('Minahonda'));
        $this->assertsame('moonglade', Utility::realmNameToSlug('Moonglade'));
        $this->assertsame('mugthol', Utility::realmNameToSlug('Mug\'thol'));
        $this->assertsame('nagrand', Utility::realmNameToSlug('Nagrand'));
        $this->assertsame('nathrezim', Utility::realmNameToSlug('Nathrezim'));
        $this->assertsame('naxxramas', Utility::realmNameToSlug('Naxxramas'));
        $this->assertsame('nazjatar', Utility::realmNameToSlug('Nazjatar'));
        $this->assertsame('nefarian', Utility::realmNameToSlug('Nefarian'));
        $this->assertsame('nemesis', Utility::realmNameToSlug('Nemesis'));
        $this->assertsame('neptulon', Utility::realmNameToSlug('Neptulon'));
        $this->assertsame('nerzhul', Utility::realmNameToSlug('Ner\'zhul'));
        $this->assertsame('nerathor', Utility::realmNameToSlug('Nera\'thor'));
        $this->assertsame('nethersturm', Utility::realmNameToSlug('Nethersturm'));
        $this->assertsame('nordrassil', Utility::realmNameToSlug('Nordrassil'));
        $this->assertsame('norgannon', Utility::realmNameToSlug('Norgannon'));
        $this->assertsame('nozdormu', Utility::realmNameToSlug('Nozdormu'));
        $this->assertsame('onyxia', Utility::realmNameToSlug('Onyxia'));
        $this->assertsame('outland', Utility::realmNameToSlug('Outland'));
        $this->assertsame('perenolde', Utility::realmNameToSlug('Perenolde'));
        $this->assertsame('pozzo-delleternita', Utility::realmNameToSlug('Pozzo dell\'Eternità'));
        $this->assertsame('proudmoore', Utility::realmNameToSlug('Proudmoore'));
        $this->assertsame('quelthalas', Utility::realmNameToSlug('Quel\'Thalas'));
        $this->assertsame('ragnaros', Utility::realmNameToSlug('Ragnaros'));
        $this->assertsame('rajaxx', Utility::realmNameToSlug('Rajaxx'));
        $this->assertsame('rashgarroth', Utility::realmNameToSlug('Rashgarroth'));
        $this->assertsame('ravencrest', Utility::realmNameToSlug('Ravencrest'));
        $this->assertsame('ravenholdt', Utility::realmNameToSlug('Ravenholdt'));
        $this->assertsame('razuvious', Utility::realmNameToSlug('Razuvious'));
        $this->assertsame('rexxar', Utility::realmNameToSlug('Rexxar'));
        $this->assertsame('runetotem', Utility::realmNameToSlug('Runetotem'));
        $this->assertsame('sanguino', Utility::realmNameToSlug('Sanguino'));
        $this->assertsame('sargeras', Utility::realmNameToSlug('Sargeras'));
        $this->assertsame('saurfang', Utility::realmNameToSlug('Saurfang'));
        $this->assertsame('scarshield-legion', Utility::realmNameToSlug('Scarshield Legion'));
        $this->assertsame('senjin', Utility::realmNameToSlug('Sen\'jin'));
        $this->assertsame('shadowsong', Utility::realmNameToSlug('Shadowsong'));
        $this->assertsame('shattered-halls', Utility::realmNameToSlug('Shattered Halls'));
        $this->assertsame('shattered-hand', Utility::realmNameToSlug('Shattered Hand'));
        $this->assertsame('shattrath', Utility::realmNameToSlug('Shattrath'));
        $this->assertsame('shendralar', Utility::realmNameToSlug('Shen\'dralar'));
        $this->assertsame('silvermoon', Utility::realmNameToSlug('Silvermoon'));
        $this->assertsame('sinstralis', Utility::realmNameToSlug('Sinstralis'));
        $this->assertsame('skullcrusher', Utility::realmNameToSlug('Skullcrusher'));
        $this->assertsame('soulflayer', Utility::realmNameToSlug('Soulflayer'));
        $this->assertsame('spinebreaker', Utility::realmNameToSlug('Spinebreaker'));
        $this->assertsame('sporeggar', Utility::realmNameToSlug('Sporeggar'));
        $this->assertsame('steamwheedle-cartel', Utility::realmNameToSlug('Steamwheedle Cartel'));
        $this->assertsame('stormrage', Utility::realmNameToSlug('Stormrage'));
        $this->assertsame('stormreaver', Utility::realmNameToSlug('Stormreaver'));
        $this->assertsame('stormscale', Utility::realmNameToSlug('Stormscale'));
        $this->assertsame('sunstrider', Utility::realmNameToSlug('Sunstrider'));
        $this->assertsame('sylvanas', Utility::realmNameToSlug('Sylvanas'));
        $this->assertsame('taerar', Utility::realmNameToSlug('Taerar'));
        $this->assertsame('talnivarr', Utility::realmNameToSlug('Talnivarr'));
        $this->assertsame('tarren-mill', Utility::realmNameToSlug('Tarren Mill'));
        $this->assertsame('teldrassil', Utility::realmNameToSlug('Teldrassil'));
        $this->assertsame('temple-noir', Utility::realmNameToSlug('Temple noir'));
        $this->assertsame('terenas', Utility::realmNameToSlug('Terenas'));
        $this->assertsame('terokkar', Utility::realmNameToSlug('Terokkar'));
        $this->assertsame('terrordar', Utility::realmNameToSlug('Terrordar'));
        $this->assertsame('the-maelstrom', Utility::realmNameToSlug('The Maelstrom'));
        $this->assertsame('the-shatar', Utility::realmNameToSlug('The Sha\'tar'));
        $this->assertsame('the-venture-co', Utility::realmNameToSlug('The Venture Co'));
        $this->assertsame('theradras', Utility::realmNameToSlug('Theradras'));
        $this->assertsame('thermaplugg', Utility::realmNameToSlug('Thermaplugg'));
        $this->assertsame('thrall', Utility::realmNameToSlug('Thrall'));
        $this->assertsame('throkferoth', Utility::realmNameToSlug('Throk\'Feroth'));
        $this->assertsame('thunderhorn', Utility::realmNameToSlug('Thunderhorn'));
        $this->assertsame('tichondrius', Utility::realmNameToSlug('Tichondrius'));
        $this->assertsame('tirion', Utility::realmNameToSlug('Tirion'));
        $this->assertsame('todeswache', Utility::realmNameToSlug('Todeswache'));
        $this->assertsame('trollbane', Utility::realmNameToSlug('Trollbane'));
        $this->assertsame('turalyon', Utility::realmNameToSlug('Turalyon'));
        $this->assertsame('twilights-hammer', Utility::realmNameToSlug('Twilight\'s Hammer'));
        $this->assertsame('twisting-nether', Utility::realmNameToSlug('Twisting Nether'));
        $this->assertsame('tyrande', Utility::realmNameToSlug('Tyrande'));
        $this->assertsame('uldaman', Utility::realmNameToSlug('Uldaman'));
        $this->assertsame('ulduar', Utility::realmNameToSlug('Ulduar'));
        $this->assertsame('uldum', Utility::realmNameToSlug('Uldum'));
        $this->assertsame('ungoro', Utility::realmNameToSlug('Un\'Goro'));
        $this->assertsame('varimathras', Utility::realmNameToSlug('Varimathras'));
        $this->assertsame('vashj', Utility::realmNameToSlug('Vashj'));
        $this->assertsame('veklor', Utility::realmNameToSlug('Vek\'lor'));
        $this->assertsame('veknilash', Utility::realmNameToSlug('Vek\'nilash'));
        $this->assertsame('voljin', Utility::realmNameToSlug('Vol\'jin'));
        $this->assertsame('wildhammer', Utility::realmNameToSlug('Wildhammer'));
        $this->assertsame('wrathbringer', Utility::realmNameToSlug('Wrathbringer'));
        $this->assertsame('xavius', Utility::realmNameToSlug('Xavius'));
        $this->assertsame('ysera', Utility::realmNameToSlug('Ysera'));
        $this->assertsame('ysondre', Utility::realmNameToSlug('Ysondre'));
        $this->assertsame('zenedar', Utility::realmNameToSlug('Zenedar'));
        $this->assertsame('zirkel-des-cenarius', Utility::realmNameToSlug('Zirkel des Cenarius'));
        $this->assertsame('zuljin', Utility::realmNameToSlug('Zul\'jin'));
        $this->assertsame('zuluhed', Utility::realmNameToSlug('Zuluhed'));
        $this->assertsame('akama', Utility::realmNameToSlug('Akama'));
        $this->assertsame('altar-of-storms', Utility::realmNameToSlug('Altar of Storms'));
        $this->assertsame('alterac-mountains', Utility::realmNameToSlug('Alterac Mountains'));
        $this->assertsame('andorhal', Utility::realmNameToSlug('Andorhal'));
        $this->assertsame('anvilmar', Utility::realmNameToSlug('Anvilmar'));
        $this->assertsame('azgalor', Utility::realmNameToSlug('Azgalor'));
        $this->assertsame('azralon', Utility::realmNameToSlug('Azralon'));
        $this->assertsame('barthilas', Utility::realmNameToSlug('Barthilas'));
        $this->assertsame('black-dragonflight', Utility::realmNameToSlug('Black Dragonflight'));
        $this->assertsame('blackwater-raiders', Utility::realmNameToSlug('Blackwater Raiders'));
        $this->assertsame('blackwing-lair', Utility::realmNameToSlug('Blackwing Lair'));
        $this->assertsame('bleeding-hollow', Utility::realmNameToSlug('Bleeding Hollow'));
        $this->assertsame('blood-furnace', Utility::realmNameToSlug('Blood Furnace'));
        $this->assertsame('bonechewer', Utility::realmNameToSlug('Bonechewer'));
        $this->assertsame('caelestrasz', Utility::realmNameToSlug('Caelestrasz'));
        $this->assertsame('cairne', Utility::realmNameToSlug('Cairne'));
        $this->assertsame('cenarion-circle', Utility::realmNameToSlug('Cenarion Circle'));
        $this->assertsame('cenarius', Utility::realmNameToSlug('Cenarius'));
        $this->assertsame('coilfang', Utility::realmNameToSlug('Coilfang'));
        $this->assertsame('dark-iron', Utility::realmNameToSlug('Dark Iron'));
        $this->assertsame('darrowmere', Utility::realmNameToSlug('Darrowmere'));
        $this->assertsame('dathremar', Utility::realmNameToSlug('Dath\'Remar'));
        $this->assertsame('dawnbringer', Utility::realmNameToSlug('Dawnbringer'));
        $this->assertsame('demon-soul', Utility::realmNameToSlug('Demon Soul'));
        $this->assertsame('detheroc', Utility::realmNameToSlug('Detheroc'));
        $this->assertsame('draktharon', Utility::realmNameToSlug('Drak\'Tharon'));
        $this->assertsame('draka', Utility::realmNameToSlug('Draka'));
        $this->assertsame('drakkari', Utility::realmNameToSlug('Drakkari'));
        $this->assertsame('dreadmaul', Utility::realmNameToSlug('Dreadmaul'));
        $this->assertsame('drenden', Utility::realmNameToSlug('Drenden'));
        $this->assertsame('duskwood', Utility::realmNameToSlug('Duskwood'));
        $this->assertsame('echo-isles', Utility::realmNameToSlug('Echo Isles'));
        $this->assertsame('farstriders', Utility::realmNameToSlug('Farstriders'));
        $this->assertsame('feathermoon', Utility::realmNameToSlug('Feathermoon'));
        $this->assertsame('fenris', Utility::realmNameToSlug('Fenris'));
        $this->assertsame('firetree', Utility::realmNameToSlug('Firetree'));
        $this->assertsame('fizzcrank', Utility::realmNameToSlug('Fizzcrank'));
        $this->assertsame('gallywix', Utility::realmNameToSlug('Gallywix'));
        $this->assertsame('garithos', Utility::realmNameToSlug('Garithos'));
        $this->assertsame('gnomeregan', Utility::realmNameToSlug('Gnomeregan'));
        $this->assertsame('gorefiend', Utility::realmNameToSlug('Gorefiend'));
        $this->assertsame('grizzly-hills', Utility::realmNameToSlug('Grizzly Hills'));
        $this->assertsame('gundrak', Utility::realmNameToSlug('Gundrak'));
        $this->assertsame('gurubashi', Utility::realmNameToSlug('Gurubashi'));
        $this->assertsame('hydraxis', Utility::realmNameToSlug('Hydraxis'));
        $this->assertsame('icecrown', Utility::realmNameToSlug('Icecrown'));
        $this->assertsame('jubeithos', Utility::realmNameToSlug('Jubei\'Thos'));
        $this->assertsame('kalecgos', Utility::realmNameToSlug('Kalecgos'));
        $this->assertsame('korgath', Utility::realmNameToSlug('Korgath'));
        $this->assertsame('korialstrasz', Utility::realmNameToSlug('Korialstrasz'));
        $this->assertsame('lethon', Utility::realmNameToSlug('Lethon'));
        $this->assertsame('lightninghoof', Utility::realmNameToSlug('Lightninghoof'));
        $this->assertsame('llane', Utility::realmNameToSlug('Llane'));
        $this->assertsame('madoran', Utility::realmNameToSlug('Madoran'));
        $this->assertsame('maelstrom', Utility::realmNameToSlug('Maelstrom'));
        $this->assertsame('maiev', Utility::realmNameToSlug('Maiev'));
        $this->assertsame('misha', Utility::realmNameToSlug('Misha'));
        $this->assertsame('moknathal', Utility::realmNameToSlug('Mok\'Nathal'));
        $this->assertsame('moon-guard', Utility::realmNameToSlug('Moon Guard'));
        $this->assertsame('moonrunner', Utility::realmNameToSlug('Moonrunner'));
        $this->assertsame('muradin', Utility::realmNameToSlug('Muradin'));
        $this->assertsame('nazgrel', Utility::realmNameToSlug('Nazgrel'));
        $this->assertsame('nesingwary', Utility::realmNameToSlug('Nesingwary'));
        $this->assertsame('queldorei', Utility::realmNameToSlug('Quel\'dorei'));
        $this->assertsame('rivendare', Utility::realmNameToSlug('Rivendare'));
        $this->assertsame('scarlet-crusade', Utility::realmNameToSlug('Scarlet Crusade'));
        $this->assertsame('scilla', Utility::realmNameToSlug('Scilla'));
        $this->assertsame('sentinels', Utility::realmNameToSlug('Sentinels'));
        $this->assertsame('shadow-council', Utility::realmNameToSlug('Shadow Council'));
        $this->assertsame('shadowmoon', Utility::realmNameToSlug('Shadowmoon'));
        $this->assertsame('shandris', Utility::realmNameToSlug('Shandris'));
        $this->assertsame('shuhalo', Utility::realmNameToSlug('Shu\'halo'));
        $this->assertsame('silver-hand', Utility::realmNameToSlug('Silver Hand'));
        $this->assertsame('sisters-of-elune', Utility::realmNameToSlug('Sisters of Elune'));
        $this->assertsame('skywall', Utility::realmNameToSlug('Skywall'));
        $this->assertsame('smolderthorn', Utility::realmNameToSlug('Smolderthorn'));
        $this->assertsame('spirestone', Utility::realmNameToSlug('Spirestone'));
        $this->assertsame('staghelm', Utility::realmNameToSlug('Staghelm'));
        $this->assertsame('stonemaul', Utility::realmNameToSlug('Stonemaul'));
        $this->assertsame('suramar', Utility::realmNameToSlug('Suramar'));
        $this->assertsame('tanaris', Utility::realmNameToSlug('Tanaris'));
        $this->assertsame('thaurissan', Utility::realmNameToSlug('Thaurissan'));
        $this->assertsame('the-forgotten-coast', Utility::realmNameToSlug('The Forgotten Coast'));
        $this->assertsame('the-scryers', Utility::realmNameToSlug('The Scryers'));
        $this->assertsame('the-underbog', Utility::realmNameToSlug('The Underbog'));
        $this->assertsame('thorium-brotherhood', Utility::realmNameToSlug('Thorium Brotherhood'));
        $this->assertsame('thunderlord', Utility::realmNameToSlug('Thunderlord'));
        $this->assertsame('tol-barad', Utility::realmNameToSlug('Tol Barad'));
        $this->assertsame('tortheldrin', Utility::realmNameToSlug('Tortheldrin'));
        $this->assertsame('undermine', Utility::realmNameToSlug('Undermine'));
        $this->assertsame('ursin', Utility::realmNameToSlug('Ursin'));
        $this->assertsame('uther', Utility::realmNameToSlug('Uther'));
        $this->assertsame('velen', Utility::realmNameToSlug('Velen'));
        $this->assertsame('warsong', Utility::realmNameToSlug('Warsong'));
        $this->assertsame('whisperwind', Utility::realmNameToSlug('Whisperwind'));
        $this->assertsame('windrunner', Utility::realmNameToSlug('Windrunner'));
        $this->assertsame('winterhoof', Utility::realmNameToSlug('Winterhoof'));
        $this->assertsame('wyrmrest-accord', Utility::realmNameToSlug('Wyrmrest Accord'));
        $this->assertsame('zangarmarsh', Utility::realmNameToSlug('Zangarmarsh'));
        $this->assertsame('데스윙', Utility::realmNameToSlug('데스윙'));
        $this->assertsame('듀로탄', Utility::realmNameToSlug('듀로탄'));
        $this->assertsame('불타는-군단', Utility::realmNameToSlug('불타는 군단'));
        $this->assertsame('세나리우스', Utility::realmNameToSlug('세나리우스'));
        $this->assertsame('아즈샤라', Utility::realmNameToSlug('아즈샤라'));
        $this->assertsame('윈드러너', Utility::realmNameToSlug('윈드러너'));
        $this->assertsame('줄진', Utility::realmNameToSlug('줄진'));
        $this->assertsame('하이잘', Utility::realmNameToSlug('하이잘'));
        $this->assertsame('헬스크림', Utility::realmNameToSlug('헬스크림'));
        $this->assertsame('世界之樹', Utility::realmNameToSlug('世界之樹'));
        $this->assertsame('亞雷戈斯', Utility::realmNameToSlug('亞雷戈斯'));
        $this->assertsame('冰霜之刺', Utility::realmNameToSlug('冰霜之刺'));
        $this->assertsame('冰風崗哨', Utility::realmNameToSlug('冰風崗哨'));
        $this->assertsame('地獄吼', Utility::realmNameToSlug('地獄吼'));
        $this->assertsame('夜空之歌', Utility::realmNameToSlug('夜空之歌'));
        $this->assertsame('天空之牆', Utility::realmNameToSlug('天空之牆'));
        $this->assertsame('寒冰皇冠', Utility::realmNameToSlug('寒冰皇冠'));
        $this->assertsame('尖石', Utility::realmNameToSlug('尖石'));
        $this->assertsame('屠魔山谷', Utility::realmNameToSlug('屠魔山谷'));
        $this->assertsame('巨龍之喉', Utility::realmNameToSlug('巨龍之喉'));
        $this->assertsame('憤怒使者', Utility::realmNameToSlug('憤怒使者'));
        $this->assertsame('日落沼澤', Utility::realmNameToSlug('日落沼澤'));
        $this->assertsame('暗影之月', Utility::realmNameToSlug('暗影之月'));
        $this->assertsame('水晶之刺', Utility::realmNameToSlug('水晶之刺'));
        $this->assertsame('狂熱之刃', Utility::realmNameToSlug('狂熱之刃'));
        $this->assertsame('眾星之子', Utility::realmNameToSlug('眾星之子'));
        $this->assertsame('米奈希爾', Utility::realmNameToSlug('米奈希爾'));
        $this->assertsame('聖光之願', Utility::realmNameToSlug('聖光之願'));
        $this->assertsame('血之谷', Utility::realmNameToSlug('血之谷'));
        $this->assertsame('語風', Utility::realmNameToSlug('語風'));
        $this->assertsame('銀翼要塞', Utility::realmNameToSlug('銀翼要塞'));
        $this->assertsame('阿薩斯', Utility::realmNameToSlug('阿薩斯'));
        $this->assertsame('雲蛟衛', Utility::realmNameToSlug('雲蛟衛'));
        $this->assertsame('雷鱗', Utility::realmNameToSlug('雷鱗'));
    }

    /**
     * @covers ::thumbnailToId
     */
    public function testThumbnailToId()
    {
        $this->assertSame('207104578511', Utility::thumbnailToId('internal-record-3702/207/104578511-avatar.jpg'));
    }

    /**
     * @covers                   ::thumbnailToId
     * @expectedException        RuntimeException
     * @expectedExceptionMessage Invalid thumbnail URL "invalid.jpg"
     */
    public function testThumbnailToIdWithInvalidUrl()
    {
        Utility::thumbnailToId('invalid.jpg');
    }
}
